---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fred-kde
description: This is my personal OS image.
base-image: ghcr.io/blue-build/base-images/fedora-kinoite-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      packages:
        - kate
        - vim
        - code
        - podman
    group-install:
      packages:
        - development-tools
        - virtualization
    remove:
      packages:
        - "*akonadi*"
        - plymouth
        - plasma-discover
  - type: systemd
    system:
      disabled:
        - plasmalogin

  - type: yafti
    custom-flatpaks:
      - Discord: com.discordapp.Discord
      - Flatseal: com.github.tchx84.Flatseal
      - Bottles: com.usebottles.bottles
      - Steam: com.valvesoftware.Steam
      - Rustdesk: com.rustdesk.RustDesk
      - Localsend: org.localsend.localsend_app
      - Remmina: org.remmina.Remmina
      - Sqlite DB Browser: org.sqlitebrowser.sqlitebrowser

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
      - scope: user

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
