---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fred-kde
description: This is my personal OS image.
base-image: ghcr.io/blue-build/base-images/fedora-kinoite-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # Workaround: akonadi-server %postun in Fedora 44 fails because update-alternatives exits with code 2
  - type: script
    snippets:
      - rpm -qa "*akonadi*" | xargs rpm -e --nodeps --noscripts
      - rm -rf /etc/xdg/akonadi /etc/alternatives/akonadiserverrc /usr/lib/systemd/system/akonadi_control.service

  - type: dnf
    remove:
      packages:
        - plymouth
        - plasma-discover

  - type: dnf
    group-install:
      packages:
        - development-tools
        - virtualization

  - type: dnf
    repos:
      nonfree: rpmfusion
    install:
      packages:
        - unrar

  - type: dnf
    repos:
      files:
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      packages:
        - code

  - type: yafti
    custom-flatpaks:
      - Discord: com.discordapp.Discord
      - Flatseal: com.github.tchx84.Flatseal
      - Bottles: com.usebottles.bottles
      - Steam: com.valvesoftware.Steam
      - Rustdesk: com.rustdesk.RustDesk
      - Localsend: org.localsend.localsend_app
      - Remmina: org.remmina.Remmina
      - Sqlite DB Browser: org.sqlitebrowser.sqlitebrowser

  - type: systemd
    system:
      enabled:
        - strip-kargs
        - sshd
      disabled:
        - plasmalogin
        - ModemManager
        - geoclue
    user:
      masked:
        - kde-baloo
        - plasma-baloorunner

  - type: dnf
    install:
      packages:
        - kate
        - vim
        - podman
        - ripgrep
        - uv
        - mpv
        - syncplay
        - ddclient
        - croc
        - steam-devices
        - podman-docker
        - markdownpart
        - transmission-show
        - jpegoptim
        - qrencode
        - innoextract
        - bmap-tools
        - mangohud
        - gh
        - 7zip

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
